#!/bin/bash -i

sudo apt install -y git yadm dialog
sudo git clone https://github.com/apajo/sysenv.git /etc/sysenv
sudo cp /etc/sysenv/sysenv /bin/sysenv

. /etc/sysenv/bin/cmd/link
source /etc/sysenv/.profile

. /etc/sysenv/bin/cmd/setup
