#!/bin/bash -i

source /etc/sysenv/.profile;

while [ $# -gt 0 ]; do
  arg=$1
echo "$arg"; exit;
    case $arg in
        "service")
            . "$ROOT/bin/cmd/service"
            exit;
        ;;
    esac

    if [ -f "$SYSENV/bin/cmd/$1" ]
    then
        source $SYSENV/bin/inc/common
        . "$ROOT/bin/cmd/$1"
        exit;
    fi

    case $arg in
        shortlist)
            echo $(find "$ROOT/bin/cmd" -maxdepth 1 -printf "%f\n")
        ;;
         *)
            route_go "menu";
        ;;
    esac
  shift
done
