#!/bin/bash -i

ROOT="$(dirname ${BASH_SOURCE[0]})"
source $ROOT/.profile
cd $ROOT;

source ./bin/inc/common
source ./bin/inc/log

while [ $# -gt 0 ]; do
  arg=$1

    if [ -f "$SYSENV/bin/cmd/$1" ]
    then
        . "$ROOT/bin/cmd/$1"
        exit;
    fi

    case $arg in
        shortlist)
            echo $(find "$ROOT/bin/cmd" -maxdepth 1 -printf "%f\n")
        ;;
        *)
            syadm $*
        ;;
    esac
  shift
done
