#!/bin/bash -i

sudo apt install -y git yadm dialog

if [ ! -d "/etc/sysenv" ] ; then
  sudo git clone https://github.com/apajo/sysenv.git /etc/sysenv
fi

sudo cp /etc/sysenv/src/sysenv /bin/sysenv

source /etc/sysenv/src/bin/inc/common;

. /etc/sysenv/src/bin/cmd/link
source /etc/sysenv/src/.profile

. /etc/sysenv/src/bin/cmd/setup
