#!/bin/bash -i

sudo apt install -y git yadm dialog

if [ ! -d "/etc/sysenv" ] ; then
  sudo git clone https://github.com/apajo/sysenv.git /etc/sysenv
fi

sudo ln -s /etc/sysenv/src/sysenv /bin/sysenv

source /etc/sysenv/src/bin/inc/common;

. /etc/sysenv/src/bin/cmd/link
. /etc/sysenv/src/bin/cmd/setup

sudo cp /etc/sysenv/src/service/init/sysenv.service /etc/systemd/system/sysenv.service
sudo systemctl daemon-reload
sudo systemctl enable sysenv.service
sudo systemctl start sysenv.service
