#!/bin/bash -i

set -e;

if [ -f "$HOME/.config/sysenv/config" ]
then
  source "$HOME/.config/sysenv/config";
fi


run () {
  source /etc/sysenv/src/bin/inc/common;
  /etc/sysenv/src/bin/cmd/$1 2>>log

  exit;
}

if [ "$1" == "" ]
then
  set -- "menu";
fi

while [ $# -gt 0 ]; do
  arg=$1

    case $arg in
        "service")
            . "/etc/sysenv/src/bin/cmd/service"
            exit;
        ;;
    esac

    if [ -f "/etc/sysenv/src/bin/cmd/$arg" ]
    then
        run "$arg";
    fi

    case $arg in
        shortlist)
            echo $(find "/etc/sysenv/src/bin/cmd" -maxdepth 1 -printf "%f\n")
        ;;
         *)
            syadm $*;
        ;;
    esac
  shift
done
