#!/bin/bash -i

source /etc/sysenv/.profile;

run () { echo "RUN:$1"
  source /etc/sysenv/bin/inc/common;
  . "$SYSENV/bin/cmd/$1"

  exit;
}

if [ "$1" == "" ]
then
  set -- "menu";
fi

while [ $# -gt 0 ]; do
  arg=$1

    case $arg in
        "service")
            . "$ROOT/bin/cmd/service"
            exit;
        ;;
    esac

    if [ -f "$SYSENV/bin/cmd/$arg" ]
    then
        run "$arg";
    fi

    case $arg in
        shortlist)
            echo $(find "$ROOT/bin/cmd" -maxdepth 1 -printf "%f\n")
        ;;
         *)
            syadm $*;
        ;;
    esac
  shift
done
